name: Changelog & Release

on:
  push:
    tags:
      - 'v*.*.*'     # np. v1.2.3
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG.md
        run: |
          npm i -g conventional-changelog-cli
          conventional-changelog -p angular -i CHANGELOG.md -s
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore(release): update CHANGELOG for $GITHUB_REF_NAME" || echo "no changes"
          git push

      - name: Create GitHub Release with notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          files: |
            CHANGELOG.md
